# Generated by Django 5.2.7 on 2025-11-02 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16)),
                ('account_type', models.CharField(choices=[('CREDI CARD', 'Credit card'), ('DEBIT CARD', 'Debit card')], default='CREDI CARD')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.client')),
            ],
        ),
    ]
